version: "3.9"
services:
 scheds-frontend:
   build:
     context: .
     dockerfile: Dockerfile.dev
   container_name: scheds-frontend
   restart: unless-stopped
   ports:
     - 3003:3003
   volumes:
     - ./:/app
     - /app/node_modules
   environment:
     - VITE_APP_BACKEND_ADDRESS=https://api.scheds.ngmunhin.com/