name: DigitalOcean

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # inputs:
    #   version:
    #     description: 'Image Version'
    #     required: true

env:
  IMAGE_NAME: "scheds-frontend"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: IMAGE_NAME,REGISTRY,{{ secrets.DIGITALOCEAN_ACCESS_TOKEN }},GITHUB_SHA
          script: |
            # cd to directory and update
            cd scheds-frontend
            git pull
            # Stop running container
            docker compose down -v
            # Build new container
            docker compose -f docker-compose.yml build --force-rm --no-cache --compress
            # Run a new container from a new image
            docker compose up -d